  name: CI
  on:
    push:
      branches: [ "master" ]
    workflow_dispatch:
  jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v4
       - name: install dependencies
         run: npm install
       - name: check code style
         run: npx prettier --check ./src
    build:
     runs-on: ubuntu-latest
     needs: [ lint ]
     steps:
       - uses: actions/checkout@v4
       - name: Run a one-line script
         run: echo ${{ secrets.TELEGRAM_TOKEN }}
